# Generated by Django 6.1 on 2026-09-09 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('consumidor', 'Consumidor'), ('comercio', 'Comercio'), ('organizacion', 'Organización')], default='consumidor', max_length=20, verbose_name='Rol de Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercio', models.CharField(max_length=150, verbose_name='Nombre Fantasía del Comercio')),
                ('cuit_cuil', models.CharField(max_length=13, unique=True, verbose_name='CUIT / CUIL')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección Comercial (Ej: Alta Gracia)')),
                ('rubro', models.CharField(help_text='Ej: Panadería, Verdulería, Supermercado', max_length=100, verbose_name='Rubro')),
                ('horario_atencion', models.CharField(help_text='Ej: Lunes a Sábados de 18:00 a 20:00 hs', max_length=100, verbose_name='Horario de Retiro de Ofertas')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_comercio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=150, verbose_name='Nombre de la Organización')),
                ('cuit_cuil', models.CharField(max_length=13, unique=True, verbose_name='CUIT / CUIL / Matrícula')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('personeria_juridica', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Personería Jurídica')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_organizacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Original ($)')),
                ('precio_descuento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio con Descuento ($)')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Cantidad / Stock Disponible')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('es_para_donacion', models.BooleanField(default=False, verbose_name='¿Apto / Marcado para Donación Gratuita?')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('donado', 'Donado'), ('agotado', 'Agotado')], default='disponible', max_length=20, verbose_name='Estado de Publicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='users.comercio', verbose_name='Comercio Propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Reservada')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total ($)')),
                ('codigo_retiro', models.CharField(max_length=10, unique=True, verbose_name='Código de Verificación para Retiro')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Retiro'), ('completado', 'Completado / Retirado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Consumidor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='users.producto', verbose_name='Producto Reservado')),
            ],
        ),
    ]
