# Generated by Django 5.2.17 on 2026-10-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_usuario_rol_alter_usuario_telefono_comercio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_entidad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_comercio', to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_organizacion', to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='consumidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='users.usuario', verbose_name='Consumidor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece este usuario.', related_name='%(app_label)s_%(class)s_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('consumidor', 'Consumidor'), ('comercio', 'Comercio'), ('organizacion', 'Organización')], default='consumidor', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='%(app_label)s_%(class)s_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
