# Generated by Django 6.1 on 2026-08-21 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fantasia', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=13)),
                ('horario_atencion', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'comercio'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
