# Generated by Django 5.2.17 on 2026-10-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_comercio_tienda'),
        ('users', '0002_alter_usuario_rol_alter_usuario_telefono_comercio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'rol': 'comercio'}, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
    ]
