# Generated by Django 6.1 on 2026-08-21 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_donacion', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('fecha_vencimiento', models.DateField()),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.comercio')),
            ],
        ),
    ]
